-- MySQL Script generated by MySQL Workbench
-- Sel 07 Jul 2020 03:20:03  WIB
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema dyspochat
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `dyspochat` ;

-- -----------------------------------------------------
-- Schema dyspochat
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `dyspochat` DEFAULT CHARACTER SET utf8 ;
USE `dyspochat` ;

-- -----------------------------------------------------
-- Table `dyspochat`.`user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dyspochat`.`user` ;

CREATE TABLE IF NOT EXISTS `dyspochat`.`user` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(32) NOT NULL,
  `password` VARCHAR(512) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `username_UNIQUE` (`username` ASC),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dyspochat`.`chatroom`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dyspochat`.`chatroom` ;

CREATE TABLE IF NOT EXISTS `dyspochat`.`chatroom` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `room_id` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  UNIQUE INDEX `room_id_UNIQUE` (`room_id` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dyspochat`.`message`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dyspochat`.`message` ;

CREATE TABLE IF NOT EXISTS `dyspochat`.`message` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `user_id` INT NOT NULL,
  `chatroom_id` INT NOT NULL,
  `content` TEXT NULL,
  PRIMARY KEY (`id`, `user_id`, `chatroom_id`),
  INDEX `fk_message_user1_idx` (`user_id` ASC),
  INDEX `fk_message_chatroom1_idx` (`chatroom_id` ASC),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  CONSTRAINT `fk_message_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `dyspochat`.`user` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_message_chatroom1`
    FOREIGN KEY (`chatroom_id`)
    REFERENCES `dyspochat`.`chatroom` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dyspochat`.`chat_recipients`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dyspochat`.`chat_recipients` ;

CREATE TABLE IF NOT EXISTS `dyspochat`.`chat_recipients` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `chatroom_id` INT NOT NULL,
  `user_id` INT NOT NULL,
  PRIMARY KEY (`id`, `chatroom_id`, `user_id`),
  INDEX `fk_chat_recipients_user_idx` (`user_id` ASC),
  INDEX `fk_chat_recipients_chatroom1_idx` (`chatroom_id` ASC),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  CONSTRAINT `fk_chat_recipients_user`
    FOREIGN KEY (`user_id`)
    REFERENCES `dyspochat`.`user` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_chat_recipients_chatroom1`
    FOREIGN KEY (`chatroom_id`)
    REFERENCES `dyspochat`.`chatroom` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
